---
# tasks file for roles/prometheus
- name: update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

- meta: flush_handlers

