---
- hosts: nginx
  vars_files: 
   - ./vars/nginx
  user: ubuntu
  become: yes
  # Updating and upgrading all packages.
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

  # Installing NginX.
    - name: Install NginX.
      apt: name=nginx state=present
      tags: nginx

  # Copying template loadbalancer.conf file to the right location.
    - name: Nginx sites-available file
      template:
        src: "./templates/{{ item.dest }}"
        dest: "/etc/nginx/sites-available/{{ item.dest }}"
        owner: ubuntu
      with_items:
        - { dest: loadbalancer.conf }
      tags: nginx

  # Removing default file so that the new loadbalancer file takes presedence.
    - name: Remove default file
      file:
        path: '/etc/nginx/sites-enabled/default'
        state: absent

  # Creating symlink sites available and sites-enabled for loadbalancer.conf
    - name: create symlink
      file:
        src: "/etc/nginx/sites-available/{{item}}"
        dest: "/etc/nginx/sites-enabled/{{item}}"
        owner: nginx
        mode: 0644
        state: link
      with_items:
        - loadbalancer.conf
        
  # Creating log files and directories.
    - name: Creates logs directory
      file: path=/var/log/nginx state=directory owner=ubuntu mode=0755

    - name: Creates nginx acess log file
      file: path=/var/log/nginx/wp_error.log owner=ubuntu mode=0755

    - name: Creates nginx error log file
      file: path=/var/log/nginx/mysql_error.log owner=ubuntu mode=0755

  # Restarting NginX
    - name: restart nginx
      service:
        name: nginx
        state: restarted




