---
- name: Setup Apache
  hosts: wordpress
  become: yes
  vars_files:
    - vars/apache.yml

  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "wordpress"
        mode: '0755'

    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify:
        - restart apache2


    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify:
        - restart apache2


    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

