---
#This is a template, the tasks below need to be added to whatever playbook uses NFS folders 
#and executed on all servers prior to whatever application is supposed to use NFS!
- hosts: all
  user: ubuntu
  become: yes
  tasks:
# Updating and upgrading all packages.
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

# Installing nfs-commons to be able to use network sharing
    - name: Installing nfs-commons
      apt: name=nfs-common state=present

# Creating directory to host the virtual folder connected to NFS server
    - name: making shared directory
      ansible.builtin.command:
        cmd: sudo mkdir -p /mnt/shared_folder

# Mounting folder to NFS server MySQL version
    - name:
      ansible.builtin.command:
        cmd: sudo mount 192.168.20.40:/mnt/mysql /mnt/shared_folder

# Mounting folder to NFS server WP version
    - name:
      ansible.builtin.command:
        cmd: sudo mount 192.168.20.40:/mnt/wp /mnt/shared_folder

      