---
- hosts: fileserver
  user: ubuntu
  become: yes
  tasks:
  # Updating and upgrading all packages.
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
  
  # Installing nfs-kernel-server package and dependencies
    - name: Installing NFS server package
      apt: name=nfs-kernel-server state=present

  # Create shared directories
    - name: Creating MySQL shared directory
      shell: |
        sudo mkdir /mnt/mysql
        sudo chown nobody:nogroup /mnt/mysql
        sudo chmod -R 777 /mnt/mysql
  
    - name: Creating WP shared directory
      shell: |
        sudo mkdir /mnt/wp
        sudo chown nobody:nogroup /mnt/wp
        sudo chmod -R 777 /mnt/wp

  # Removing old exports file and replacing it with template
    - name: Remove legacy exports file
      file:
        path: '/etc/exports'
        state: absent

    - name: Copying template exports file to location /etc/exports
      ansible.builtin.copy:
        src: ./templates/exports
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'

  # Exporting the directories to the network
    - name: Exporting directories.
      ansible.builtin.command:
        cmd: sudo exportfs -a

  # Allowing incoming traffic on port 2049 to entire private network.
    - name: Setting up UFW rule
      ansible.builtin.command:
        cmd: sudo ufw allow from 192.168.2.0/24 to any port nfs
