---
- hosts: nginx
  vars_files: 
   - ./vars/all
  user: ubuntu
  become: yes
  
  # Wait for dpkg lock to be absent
  tasks:
    - name: Wait until the lock file is removed
      wait_for:
        path: /var/lib/dpkg/lock-frontend
        state: absent

# Updating and upgrading all packages.
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

  # Installing NginX.
    - name: Install NginX.
      apt: name=nginx state=present
      tags: nginx

  # Starting Nginx
    - name: restart nginx
      ansible.builtin.command:
        cmd: sudo service nginx start

  # Removing default nginx conf.
    - name: Remove default file
      file:
        path: '/etc/nginx/nginx.conf'
        state: absent

  # Copying the new file in  
    - name: Copy a new "ntp.conf" file into place, backing up the original if it differs from the copied version
      ansible.builtin.copy:
        src: ./templates/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

  # Copying template loadbalancer.conf file to the right location.
    - name: Nginx sites-available file
      ansible.builtin.copy:
        src: ./templates/loadbalancer.conf
        dest: /etc/nginx/conf.d/loadbalancer.conf
      with_items:
        - { dest: loadbalancer.conf }
      tags: nginx

  # Copying template mysql_loadbalancer.conf file to the right location.
    - name: Nginx sites-available file
      ansible.builtin.copy:
        src: ./templates/mysql_loadbalancer.conf
        dest: /etc/nginx/conf.d/mysql_loadbalancer.conf
      with_items:
        - { dest: mysql_loadbalancer.conf }
      tags: nginx

  # Removing default file so that the new loadbalancer file takes presedence.
    - name: Remove default file
      file:
        path: '/etc/nginx/sites-enabled/default'
        state: absent
  # Restarting NginX
    - name: restart nginx
      ansible.builtin.command:
        cmd: sudo nginx -s reload




        




