# From this guide: https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-wordpress-with-lamp-on-ubuntu-18-04
---
- hosts: wordpress
  user: ubuntu
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]

    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'libapache2-mod-php' ]
      tags: [ system ]

    - name: Install PHP and extensions.
      shell: |
        sudo apt -y install php7.4
        sudo apt -y install php7.4-curl php7.4-gd php7.4-mbstring php7.4-xml php7.4-xmlrpc php7.4-soap php7.4-intl php7.4-zip php7.4-mysql


  # Apache Configuration
    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ apache ]

    - name: Set up Apache VirtualHost
      template:
        src: "./files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache
      tags: [ apache ]

    - name: Enable rewrite module
      shell: /usr/sbin/a2enmod rewrite
      notify: Reload Apache
      tags: [ apache ]

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache
      tags: [ apache ]

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Restart Apache
      tags: [ apache ]

  # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
      tags: [ system ]

  # WordPress Configuration
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/wordpress-5.4.7.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
      tags: [ wordpress ]

    - name: Set ownership
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]

    - name: Set up wp-config
      template:
        src: "templates/wp-config.php"
        dest: "/var/www/{{ http_host }}/wp-config.php"
      tags: [ wordpress ]

      # Create directory for db conf files
    #- name: Create dir wp-content
    #  file:
    #    path: /var/www/{{ http_host }}/wp-content
    #    state: directory

      # Copy db conf files
    - name: Create db-config.php
      copy: src=/home/ubuntu/Ansible/templates/db-config.php dest=/var/www/{{ http_host }}/db-config.php

    - name: Copy db.php
      copy: src=/home/ubuntu/Ansible/templates/db.php dest=/var/www/{{ http_host }}/wp-content/db.php

    - name: copy wp-config.php
      copy: src=/home/ubuntu/Ansible/templates/wp-config.php dest=/var/www/{{ http_host }}/wp-config.php

    - name: Ensure directories are 0755
      command: sudo find /var/www/{{ http_host }}/ -type d -exec chmod 0755 {} \;

    - name: Ensure files are 0644
      command: sudo find /var/www/{{ http_host }}/ -type f -exec chmod 0644 {} \;  

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
