---
- hosts: localhost
  vars_files:
  # File which holds the variables used
   - ./vars/all
  tasks:
  # Creating the network, naming it, specifying which of the clouds in the clouds.yaml file to use and setting state to present.
    - name: Create Network
      os_network:
        cloud: "{{ cloud }}"
        name: "{{ base }}-net"
        state: present  
  # Creating the subnet, naming it, specifying which cloud in the clouds.yaml to use.
  # Specifying which network it is connected too, cidr range and dns_name servers, setting state to present.
    - name: Create SubNet
      os_subnet:
        cloud: "{{ cloud }}"
        name: "{{ base }}-subnet"
        network_name: "{{ base }}-net"
        cidr: "{{ cidr_range }}"
        dns_nameservers: 
          - 8.8.8.8
          - 8.8.4.4
        state: present
  # Creating a router to the internet, naming the router, specifying which network to connect to(public) and setting which subnet that uses the router.
  # Also setting the state to present.
    - name: Create Router
      os_router:
        cloud: "{{ cloud }}"
        name: "{{ base }}-net"
        network: public
        interfaces:
          - "{{ base }}-subnet"
        state: present
        
